-- MySQL Script generated by MySQL Workbench
-- Sat Oct  7 18:35:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema interactivegame_nasayuwe
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `interactivegame_nasayuwe` ;

-- -----------------------------------------------------
-- Schema interactivegame_nasayuwe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `interactivegame_nasayuwe` DEFAULT CHARACTER SET utf8mb3 ;
USE `interactivegame_nasayuwe` ;

-- -----------------------------------------------------
-- Table `interactivegame_nasayuwe`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactivegame_nasayuwe`.`user_role` (
  `user_ro_id` INT NOT NULL AUTO_INCREMENT,
  `user_ro_description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_ro_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `interactivegame_nasayuwe`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactivegame_nasayuwe`.`usuario` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NOT NULL,
  `user_age` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_role_user_ro_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_role_user_ro_id`),
  INDEX `fk_user_user_role1_idx` (`user_role_user_ro_id` ASC),
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_user_ro_id`)
    REFERENCES `interactivegame_nasayuwe`.`user_role` (`user_ro_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `interactivegame_nasayuwe`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactivegame_nasayuwe`.`game` (
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `game_time` DATETIME(6) NOT NULL,
  `game_ty_id` INT NOT NULL,
  `user_user_id` INT NOT NULL,
  `estado` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`game_id`, `user_user_id`),
  INDEX `fk_game_user_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_game_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `interactivegame_nasayuwe`.`usuario` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `interactivegame_nasayuwe`.`game_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactivegame_nasayuwe`.`game_type` (
  `game_ty_id` INT NOT NULL AUTO_INCREMENT,
  `game_ty_description` VARCHAR(255) NOT NULL,
  `game_ty_level` INT NOT NULL,
  `game_ty_puntos` INT NOT NULL,
  `game_ty_records` INT NOT NULL,
  `game_ty_tiempo` INT NOT NULL,
  PRIMARY KEY (`game_ty_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `interactivegame_nasayuwe`.`words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactivegame_nasayuwe`.`words` (
  `word_id` INT NOT NULL AUTO_INCREMENT,
  `word_description` VARCHAR(255) NOT NULL,
  `word_spanish_meaning` VARCHAR(255) NOT NULL,
  `word_sound` VARCHAR(255),
  `word_play` VARCHAR(255),
  `word_graph` VARCHAR(255),
  `nomFoto` varchar(1000) COLLATE utf8_spanish2_ci DEFAULT NULL,
  `foto` longblob,
  PRIMARY KEY (`word_id`),
  UNIQUE INDEX `word_sound_UNIQUE` (`word_spanish_meaning` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `interactivegame_nasayuwe`.`wordsGame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interactivegame_nasayuwe`.`wordsGame` (
  `word_id` VARCHAR(25) NOT NULL,
  `word_description` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(20) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use interactivegame_nasayuwe;
insert into user_role (user_ro_description) values ('Administrador');
insert into user_role (user_ro_description) values ('Estudiante');
insert into usuario (user_name, user_age, user_password, user_role_user_ro_id) 
values ('SYSADMIN',  '0', '870262c5e542829bad0ca83ea39e4631df4a9691', (SELECT user_ro_id FROM user_role WHERE user_ro_description = 'Administrador'));

